#R Packages and Memory
#installs a necessary packages
install.packages("openxlsx")
install.packages("rtools")
install.packages("car") 
install.packages("aod")
install.packages("plyr")
install.packages("cluster")
install.packages("fpc")
install.packages("rJava")
install.packages("ggplot2")
install.packages("pryr")
install.packages("devtools")
install.packages("plotly")
install.packages("xlsx")
install.packages("lubridate")
install.packages("extrafont")
#Load libraries of installed packages
library(lubridate)
library(rJava)
library(xlsx)
library(openxlsx)
library(car) 
library(aod)
library(g.data)
library(plyr)
library(cluster)
library(fpc)
library(ggplot2)
library(pryr)
library(devtools)
library(extrafont)
## Increase memory to view normalized data
memory.limit()
memory.limit(size=400000000)
